symbolPreset: nerd
theme: 
  dark: anthracite
setupVersion: 1
modelRoles: 
  vision: google-antigravity/gemini-3.1-flash-lite
  smol: opencode-zen/mimo-v2.5-free:medium
  default: opencode-zen/deepseek-v4-flash-free
  commit: opencode-zen/deepseek-v4-flash-free
  advisor: google-antigravity/gemini-3.6-flash
lsp: 
  formatOnWrite: true
defaultThinkingLevel: auto
hideThinkingBlock: false
extensions: 
  - ~/.omp/agent/extensions/permission-gate/src/permission-gate.ts
  - ~/.omp/agent/extensions/terminal-bell/src/index.ts
disabledExtensions: 
  - extension-module:bash-policy
github: 
  enabled: true
browser: 
  headless: false
dev: 
  autoqaConsent: granted
tui: 
  textSizing: false
display: 
  showTokenUsage: true
providers: 
  tts: auto
  imageOrder: 
    - openai-codex
    - antigravity
  webSearchGeminiModel: gemini-3.6-flash
  webSearchOrder: 
    - gemini
    - firecrawl
    - duckduckgo
    - startpage
    - ecosia
speech: 
  voice: af_heart
generate_image: 
  enabled: true
statusLine: 
  compactThinkingLevel: true
